version: "2"
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: false
      # Apply the rewrite rules to the source before reformatting.
      # https://pkg.go.dev/cmd/gofmt
      # Default: []
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'
    gofumpt:
      module-path: github.com/naivary/omp
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/naivary/omp
    golines:
      max-len: 150
      # Length of a tabulation.
      # Default: 4
      tab-len: 2
      # Shorten single-line comments.
      # Default: false
      shorten-comments: true
